### ISSUE TITLE
Write tests for createNearAccount RPC

### ISSUE THREAD

**Issue by Sladuca** [bafnetwork/baf-wallet#14]
## Problem
though a rough implementation of createNearAccount has been written, it has not yet been tested.

## Solution
write some tests for it.

## Tasks
test each of the following things. all failures and responses should follow the [JSON-RPC v2.0 spec](https://www.jsonrpc.org/specification).
- [ ] fails when no user is logged in
- [ ] fails when the logged-in user is not authorized to create a "web3" account
- [ ] fails with a helpful message when requested account ID does not exist
- [ ] fails when the logged-in user already has a linked "web3" account
- [ ] created account is of the form `name.WALLET_ACCOUNT_ID` when it succeeds
