### ISSUE TITLE
Email verification

### ISSUE THREAD

**Issue by Sladuca** [bafnetwork/baf-wallet#17]
## Problem
BAF wallet dosen't yet verify emails by sending new users emails when they sign up.

## Solution
Scope out possible email API services, pick one, propose your decision here, then integrate it into `/signup` such that the handler for `/signup` sends an email after a successful account creation but also [make it injectible](https://users.rust-lang.org/t/how-do-you-implement-dependency-injection-in-rust/213) so whatever email-sending API we use can be stubbed out during testing

## Tasks
to-do list of things that need to happen in order to implement said solution
- [ ] choose which email-sender API to use
- [ ] define an `Emailer` trait
- [ ] implement `Emailer` for email-sender API
- [ ] implement stub `Emailer`
- [ ] add an argument to `/signup` that takes an `Emailer` trait object so either the stub or the actual implementation can be put in
