### ISSUE TITLE
implement signTx RPC

### ISSUE THREAD

**Issue by Sladuca** [bafnetwork/baf-wallet#2]
## Problem
signTx RPC is not yet implemented

## Solution
implement [`sign_transaction`](https://github.com/bafnetwork/baf-progressive-wallet/blob/45f3ac290007c899fcbd4ee4b7120620d75ec923/src/keystore.rs#L149) for serialized transaction bytes.

## Tasks
- [ ] define `SignTxArgs` in a manner similar to [`SignupArgs`](https://github.com/bafnetwork/baf-progressive-wallet/blob/45f3ac290007c899fcbd4ee4b7120620d75ec923/src/web2.rs#L29), but for serialized transaction bytes sent by the client, presumably in a `Vec<u8>`
- [ ] implement the trait `From<serde_json::Value>` for `SignTxArgs` - this is necessary because the [`JsonRpc`](https://github.com/bafnetwork/baf-progressive-wallet/blob/45f3ac290007c899fcbd4ee4b7120620d75ec923/src/util.rs#L32) struct that is given as an argument to `sign_transaction` contains `serde_json::Value` struct in its `params` field if there are any params.
- [ ] implement [`sign_transaction`](https://github.com/bafnetwork/baf-progressive-wallet/blob/45f3ac290007c899fcbd4ee4b7120620d75ec923/src/keystore.rs#L149) using the trait implementation from the previous step, getting the keys from the database and doing any necessary decryption in the process.
