### ISSUE TITLE
Endpoint that allows for users to create account once authorized

### ISSUE THREAD

**Issue by Lev-Stambler** [bafnetwork/baf-wallet#23]
## Problem
We need a endpoint that allows authorized users to create their NEAR accounts once. The initial funds for their new account comes from the owner's (the account which authorized the user) wallet.

## Solution
Implement the RPC createNearAccount endpoint

## Tasks
to-do list of things that need to happen in order to implement said solution
- [ ] Check if the user is authorized
- [ ] Check that the user has not already created their account. I.e. ensure that the authorization for the user has not already been used
- [ ] Transfer funds from the owners into the new wallet
- [ ] Thorough testing 
...
