### ISSUE TITLE
Access wallet's NEAR account via environment variables

### ISSUE THREAD

**Issue by Sladuca** [bafnetwork/baf-wallet#6]
## Problem
In order for the wallet to create NEAR accounts and initialize them with the minimum balance, the wallet needs to have a NEAR account of its own. 

## Solution
For now, let's add do this with two environment variables:

- `WALLET_ACCOUNT_ID`: `String` - accountID of the NEAR account the wallet should use
- `WALLET_ACCOUNT_KEYS`: `String` - absolute path to a `.json` keyfile in the format produced by `near-cli`. 

## Tasks
to-do list of things that need to happen in order to implement said solution
- [x] add `WALLET_ACCOUNT_ID` static global constant initialized using the [`lazy_static`](https://docs.rs/lazy_static/1.4.0/lazy_static/) crate
- [x] add `WALLET_ACCOUNT_KEYS` static global constant initialized using the [`lazy_static`](https://docs.rs/lazy_static/1.4.0/lazy_static/) crate
- [x] add `fn get_wallet_keys() -> (PublicKey, SecretKey)` that reads the keys from the file at `WALLET_ACCOUNT_KEYS` and converts them into `(PublicKey, SecretKey)` pair whose types are from `sodiumoxide::crypto::sign::ed25519`[https://docs.rs/sodiumoxide/0.2.6/sodiumoxide/crypto/sign/ed25519/index.html]
